# https://circleci.com/docs/2.0/language-go/
version: 2
jobs:
  build-golang-latest:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build-golang-1_11:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
workflows:
  version: 2
  build:
    jobs:
      - build-golang-latest
      - build-golang-1_11
